backend:
  name: git-gateway
  branch: main

site_url: https://pinkpigeonpink.netlify.app

media_folder: "src/images/blog"
public_folder: "/src/images/blog"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Publish Date", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Author", name: "author", widget: "string", default: "Pink Pigeon" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - { label: "URL", name: "url", widget: "image" }
          - { label: "Alt Text", name: "alt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

